SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';


-- -----------------------------------------------------
-- Data Base `VICAL`
-- -----------------------------------------------------
DROP DATABASE IF EXISTS VICAL;

CREATE DATABASE VICAL DEFAULT CHARACTER SET latin1 COLLATE latin1_bin;

USE VICAL;

-- -----------------------------------------------------
-- Table `PRECIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PRECIO` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `PRECIO` (
  `PRECIO_UNITARIO` FLOAT NOT NULL DEFAULT '1.2' )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `RECOLECTORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RECOLECTORES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `RECOLECTORES` (
  `CODIGO_RECOLECTOR` CHAR(5) NOT NULL ,
  `NOMBRE_RECOLECTOR` VARCHAR(50) NULL DEFAULT NULL ,
  `TELEFONO_RECOLECTOR` VARCHAR(10) NULL DEFAULT NULL ,
  `DUI_RECOLECTOR` VARCHAR(10) NULL DEFAULT NULL ,
  `NIT_RECOLECTOR` VARCHAR(17) NULL DEFAULT NULL ,
  `DIRECCION_RECOLECTOR` VARCHAR(100) NULL DEFAULT NULL ,
  PRIMARY KEY (`CODIGO_RECOLECTOR`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CENTROS_DE_ACOPIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CENTROS_DE_ACOPIO` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `CENTROS_DE_ACOPIO` (
  `CODIGO_CENTRO_ACOPIO` CHAR(6) NOT NULL ,
  `CODIGO_RECOLECTOR` CHAR(5) NOT NULL ,
  `DIRECCION` VARCHAR(100) NULL DEFAULT NULL ,
  `DEPARTAMENTO` VARCHAR(50) NULL DEFAULT NULL ,
  `TELEFONO` VARCHAR(10) NULL DEFAULT NULL ,
  PRIMARY KEY (`CODIGO_CENTRO_ACOPIO`) ,
  CONSTRAINT `FK_ADMINISTRA`
    FOREIGN KEY (`CODIGO_RECOLECTOR` )
    REFERENCES `VICAL`.`RECOLECTORES` (`CODIGO_RECOLECTOR` )
    ON DELETE restrict
    ON UPDATE restrict)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `FK_ADMINISTRA` ON `CENTROS_DE_ACOPIO` (`CODIGO_RECOLECTOR` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `COLORES_VIDRIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `COLORES_VIDRIO` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `COLORES_VIDRIO` (
  `CODIGO_COLOR` CHAR(5) NOT NULL ,
  `NOMBRE_COLOR` VARCHAR(10) NULL DEFAULT NULL ,
  PRIMARY KEY (`CODIGO_COLOR`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TIPOS_EMPRESAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TIPOS_EMPRESAS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `TIPOS_EMPRESAS` (
  `CODIGO_TIPO_EMPRESA` CHAR(5) NOT NULL ,
  `NOMBRE_TIPO_EMPRESA` VARCHAR(50) NULL DEFAULT NULL ,
  PRIMARY KEY (`CODIGO_TIPO_EMPRESA`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PROVEEDORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROVEEDORES` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `PROVEEDORES` (
  `CODIGO_PROVEEDOR` INT(5) NOT NULL AUTO_INCREMENT ,
  `CODIGO_TIPO_EMPRESA` CHAR(5) NOT NULL ,
  `NOMBRE_PROVEEDOR` VARCHAR(50) NULL DEFAULT NULL ,
  `DEPARTAMENTO` VARCHAR(50) NULL DEFAULT NULL ,
  `DIRECCION_PROVEEDOR` VARCHAR(100) NULL DEFAULT NULL ,
  `TELEFONO_PROVEEDOR1` VARCHAR(10) NULL DEFAULT NULL ,
  `TELEFONO_PROVEEDOR2` VARCHAR(10) NULL DEFAULT NULL ,
  `CONTACTO` VARCHAR(50) NULL DEFAULT NULL ,
  `ESTANON` VARCHAR(5) NULL DEFAULT NULL ,
  PRIMARY KEY (`CODIGO_PROVEEDOR`) ,
  CONSTRAINT `FK_ESPECIFICA`
    FOREIGN KEY (`CODIGO_TIPO_EMPRESA` )
    REFERENCES `VICAL`.`TIPOS_EMPRESAS` (`CODIGO_TIPO_EMPRESA` )
    ON DELETE restrict
    ON UPDATE restrict)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `FK_ESPECIFICA` ON `PROVEEDORES` (`CODIGO_TIPO_EMPRESA` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `FACTURAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FACTURAS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `FACTURAS` (
  `CODIGO_FACTURA` CHAR(5) NOT NULL ,
  `CODIGO_PROVEEDOR` INT(5) NOT NULL ,
  `CODIGO_RECOLECTOR` CHAR(5) NOT NULL ,
  `SUCURSAL` VARCHAR(6) NOT NULL ,
  `FECHA` DATE NULL DEFAULT NULL ,
  PRIMARY KEY (`CODIGO_FACTURA`) ,
  CONSTRAINT `FK_REGISTRA`
    FOREIGN KEY (`CODIGO_RECOLECTOR` )
    REFERENCES `VICAL`.`RECOLECTORES` (`CODIGO_RECOLECTOR` )
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_GUARDA`
    FOREIGN KEY (`CODIGO_PROVEEDOR` )
    REFERENCES `VICAL`.`PROVEEDORES` (`CODIGO_PROVEEDOR` )
    ON DELETE restrict
    ON UPDATE restrict)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `FK_REGISTRA` ON `FACTURAS` (`CODIGO_RECOLECTOR` ASC) ;

SHOW WARNINGS;
CREATE INDEX `FK_GUARDA` ON `FACTURAS` (`CODIGO_PROVEEDOR` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `COMPRAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `COMPRAS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `COMPRAS` (
  `CODIGO_COMPRA` INT(5) NOT NULL AUTO_INCREMENT ,
  `CODIGO_FACTURA` CHAR(5) NOT NULL ,
  PRIMARY KEY (`CODIGO_COMPRA`) ,
  CONSTRAINT `FK_REALIZA`
    FOREIGN KEY (`CODIGO_FACTURA` )
    REFERENCES `VICAL`.`FACTURAS` (`CODIGO_FACTURA` )
    ON DELETE restrict
    ON UPDATE restrict)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `FK_REALIZA` ON `COMPRAS` (`CODIGO_FACTURA` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TIPOS_VIDRIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TIPOS_VIDRIO` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `TIPOS_VIDRIO` (
  `CODIGO_TIPO` VARCHAR(5) NOT NULL ,
  `NOMBRE_TIPO` VARCHAR(50) NULL DEFAULT NULL ,
  PRIMARY KEY (`CODIGO_TIPO`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIOS` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `USUARIOS` (
  `ID` INT(5) NOT NULL AUTO_INCREMENT ,
  `NOMBRE` VARCHAR(50) NOT NULL ,
  `USUARIO` VARCHAR(15) NOT NULL ,
  `PASSWORD` VARCHAR(15) NOT NULL ,
  `NIVEL` INT(5) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `VIDRIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VIDRIO` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `VIDRIO` (
  `CODIGO_VIDRIO` INT(5) NOT NULL AUTO_INCREMENT ,
  `CODIGO_TIPO` VARCHAR(5) NOT NULL ,
  `CODIGO_COLOR` CHAR(5) NOT NULL ,
  `CODIGO_FACTURA` CHAR(5) NOT NULL ,
  `CANTIDAD_VIDRIO` FLOAT NULL DEFAULT NULL ,
  `PRECIO` FLOAT NULL DEFAULT NULL ,
  PRIMARY KEY (`CODIGO_VIDRIO`) ,
  CONSTRAINT `FK_DETALLA`
    FOREIGN KEY (`CODIGO_COLOR` )
    REFERENCES `VICAL`.`COLORES_VIDRIO` (`CODIGO_COLOR` )
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_INCLUYE`
    FOREIGN KEY (`CODIGO_TIPO` )
    REFERENCES `VICAL`.`TIPOS_VIDRIO` (`CODIGO_TIPO` )
    ON DELETE restrict
    ON UPDATE restrict,
  CONSTRAINT `FK_POSEE`
    FOREIGN KEY (`CODIGO_FACTURA` )
    REFERENCES `VICAL`.`FACTURAS` (`CODIGO_FACTURA` )
    ON DELETE restrict
    ON UPDATE restrict)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `FK_DETALLA` ON `VIDRIO` (`CODIGO_COLOR` ASC) ;

SHOW WARNINGS;
CREATE INDEX `FK_INCLUYE` ON `VIDRIO` (`CODIGO_TIPO` ASC) ;

SHOW WARNINGS;
CREATE INDEX `FK_POSEE` ON `VIDRIO` (`CODIGO_FACTURA` ASC) ;

SHOW WARNINGS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
