CREATE USER 'vidrio'@'localhost' IDENTIFIED BY 'ciclopentanoperhidrofenantreno';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, ALTER,
SHOW DATABASES ON * . * TO 'vidrio'@'localhost' IDENTIFIED BY 'ciclopentanoperhidrofenantreno'
WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;